package com.google.zxing.oned;

import java.util.ArrayList;
import java.util.List;
import m54207b69;

final class EANManufacturerOrgSupport
{
  private final List countryIdentifiers;
  private final List ranges;
  
  public EANManufacturerOrgSupport()
  {
    ArrayList localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    this.ranges = localArrayList;
    localArrayList = new java/util/ArrayList;
    localArrayList.<init>();
    this.countryIdentifiers = localArrayList;
  }
  
  private void add(int[] paramArrayOfInt, String paramString)
  {
    this.ranges.add(paramArrayOfInt);
    this.countryIdentifiers.add(paramString);
  }
  
  private void initIfNeeded()
  {
    try
    {
      Object localObject1 = this.ranges;
      boolean bool = ((List)localObject1).isEmpty();
      if (!bool) {
        return;
      }
      bool = false;
      localObject1 = null;
      int j = 19;
      localObject1 = new int[] { 0, j };
      String str = ";_0A0D721F22";
      str = m54207b69.F54207b69_11(str);
      add((int[])localObject1, str);
      int i = 30;
      j = 39;
      localObject1 = new int[] { i, j };
      str = "US";
      add((int[])localObject1, str);
      i = 60;
      j = 139;
      localObject1 = new int[] { i, j };
      str = ";_0A0D721F22";
      str = m54207b69.F54207b69_11(str);
      add((int[])localObject1, str);
      i = 300;
      j = 379;
      localObject1 = new int[] { i, j };
      str = "FR";
      add((int[])localObject1, str);
      i = 380;
      localObject1 = new int[] { i };
      str = "BG";
      add((int[])localObject1, str);
      i = 383;
      localObject1 = new int[] { i };
      str = "SI";
      add((int[])localObject1, str);
      i = 385;
      localObject1 = new int[] { i };
      str = "HR";
      add((int[])localObject1, str);
      i = 387;
      localObject1 = new int[] { i };
      str = "BA";
      add((int[])localObject1, str);
      i = 400;
      j = 440;
      localObject1 = new int[] { i, j };
      str = "DE";
      add((int[])localObject1, str);
      i = 450;
      j = 459;
      localObject1 = new int[] { i, j };
      str = "JP";
      add((int[])localObject1, str);
      i = 460;
      j = 469;
      localObject1 = new int[] { i, j };
      str = "RU";
      add((int[])localObject1, str);
      i = 471;
      localObject1 = new int[] { i };
      str = "TW";
      add((int[])localObject1, str);
      i = 474;
      localObject1 = new int[] { i };
      str = "EE";
      add((int[])localObject1, str);
      i = 475;
      localObject1 = new int[] { i };
      str = "LV";
      add((int[])localObject1, str);
      i = 476;
      localObject1 = new int[] { i };
      str = "AZ";
      add((int[])localObject1, str);
      i = 477;
      localObject1 = new int[] { i };
      str = "LT";
      add((int[])localObject1, str);
      i = 478;
      localObject1 = new int[] { i };
      str = "UZ";
      add((int[])localObject1, str);
      i = 479;
      localObject1 = new int[] { i };
      str = "LK";
      add((int[])localObject1, str);
      i = 480;
      localObject1 = new int[] { i };
      str = "PH";
      add((int[])localObject1, str);
      i = 481;
      localObject1 = new int[] { i };
      str = "BY";
      add((int[])localObject1, str);
      i = 482;
      localObject1 = new int[] { i };
      str = "UA";
      add((int[])localObject1, str);
      i = 484;
      localObject1 = new int[] { i };
      str = "MD";
      add((int[])localObject1, str);
      i = 485;
      localObject1 = new int[] { i };
      str = "AM";
      add((int[])localObject1, str);
      i = 486;
      localObject1 = new int[] { i };
      str = "GE";
      add((int[])localObject1, str);
      i = 487;
      localObject1 = new int[] { i };
      str = "KZ";
      add((int[])localObject1, str);
      i = 489;
      localObject1 = new int[] { i };
      str = "HK";
      add((int[])localObject1, str);
      i = 490;
      j = 499;
      localObject1 = new int[] { i, j };
      str = "JP";
      add((int[])localObject1, str);
      i = 500;
      j = 509;
      localObject1 = new int[] { i, j };
      str = "GB";
      add((int[])localObject1, str);
      i = 520;
      localObject1 = new int[] { i };
      str = "GR";
      add((int[])localObject1, str);
      i = 528;
      localObject1 = new int[] { i };
      str = "LB";
      add((int[])localObject1, str);
      i = 529;
      localObject1 = new int[] { i };
      str = "CY";
      add((int[])localObject1, str);
      i = 531;
      localObject1 = new int[] { i };
      str = "MK";
      add((int[])localObject1, str);
      i = 535;
      localObject1 = new int[] { i };
      str = "MT";
      add((int[])localObject1, str);
      i = 539;
      localObject1 = new int[] { i };
      str = "IE";
      add((int[])localObject1, str);
      i = 540;
      j = 549;
      localObject1 = new int[] { i, j };
      str = "P<7E7A15736D";
      str = m54207b69.F54207b69_11(str);
      add((int[])localObject1, str);
      i = 560;
      localObject1 = new int[] { i };
      str = "PT";
      add((int[])localObject1, str);
      i = 569;
      localObject1 = new int[] { i };
      str = "IS";
      add((int[])localObject1, str);
      i = 570;
      j = 579;
      localObject1 = new int[] { i, j };
      str = "DK";
      add((int[])localObject1, str);
      i = 590;
      localObject1 = new int[] { i };
      str = "PL";
      add((int[])localObject1, str);
      i = 594;
      localObject1 = new int[] { i };
      str = "RO";
      add((int[])localObject1, str);
      i = 599;
      localObject1 = new int[] { i };
      str = "HU";
      add((int[])localObject1, str);
      i = 600;
      j = 601;
      localObject1 = new int[] { i, j };
      str = "ZA";
      add((int[])localObject1, str);
      i = 603;
      localObject1 = new int[] { i };
      str = "GH";
      add((int[])localObject1, str);
      i = 608;
      localObject1 = new int[] { i };
      str = "BH";
      add((int[])localObject1, str);
      i = 609;
      localObject1 = new int[] { i };
      str = "MU";
      add((int[])localObject1, str);
      i = 611;
      localObject1 = new int[] { i };
      str = "MA";
      add((int[])localObject1, str);
      i = 613;
      localObject1 = new int[] { i };
      str = "DZ";
      add((int[])localObject1, str);
      i = 616;
      localObject1 = new int[] { i };
      str = "KE";
      add((int[])localObject1, str);
      i = 618;
      localObject1 = new int[] { i };
      str = "CI";
      add((int[])localObject1, str);
      i = 619;
      localObject1 = new int[] { i };
      str = "TN";
      add((int[])localObject1, str);
      i = 621;
      localObject1 = new int[] { i };
      str = "SY";
      add((int[])localObject1, str);
      i = 622;
      localObject1 = new int[] { i };
      str = "EG";
      add((int[])localObject1, str);
      i = 624;
      localObject1 = new int[] { i };
      str = "LY";
      add((int[])localObject1, str);
      i = 625;
      localObject1 = new int[] { i };
      str = "JO";
      add((int[])localObject1, str);
      i = 626;
      localObject1 = new int[] { i };
      str = "IR";
      add((int[])localObject1, str);
      i = 627;
      localObject1 = new int[] { i };
      str = "KW";
      add((int[])localObject1, str);
      i = 628;
      localObject1 = new int[] { i };
      str = "SA";
      add((int[])localObject1, str);
      i = 629;
      localObject1 = new int[] { i };
      str = "AE";
      add((int[])localObject1, str);
      i = 640;
      j = 649;
      localObject1 = new int[] { i, j };
      str = "FI";
      add((int[])localObject1, str);
      i = 690;
      j = 695;
      localObject1 = new int[] { i, j };
      str = "CN";
      add((int[])localObject1, str);
      i = 700;
      j = 709;
      localObject1 = new int[] { i, j };
      str = "NO";
      add((int[])localObject1, str);
      i = 729;
      localObject1 = new int[] { i };
      str = "IL";
      add((int[])localObject1, str);
      i = 730;
      j = 739;
      localObject1 = new int[] { i, j };
      str = "SE";
      add((int[])localObject1, str);
      i = 740;
      localObject1 = new int[] { i };
      str = "GT";
      add((int[])localObject1, str);
      i = 741;
      localObject1 = new int[] { i };
      str = "SV";
      add((int[])localObject1, str);
      i = 742;
      localObject1 = new int[] { i };
      str = "HN";
      add((int[])localObject1, str);
      i = 743;
      localObject1 = new int[] { i };
      str = "NI";
      add((int[])localObject1, str);
      i = 744;
      localObject1 = new int[] { i };
      str = "CR";
      add((int[])localObject1, str);
      i = 745;
      localObject1 = new int[] { i };
      str = "PA";
      add((int[])localObject1, str);
      i = 746;
      localObject1 = new int[] { i };
      str = "DO";
      add((int[])localObject1, str);
      i = 750;
      localObject1 = new int[] { i };
      str = "MX";
      add((int[])localObject1, str);
      i = 754;
      j = 755;
      localObject1 = new int[] { i, j };
      str = "CA";
      add((int[])localObject1, str);
      i = 759;
      localObject1 = new int[] { i };
      str = "VE";
      add((int[])localObject1, str);
      i = 760;
      j = 769;
      localObject1 = new int[] { i, j };
      str = "CH";
      add((int[])localObject1, str);
      i = 770;
      localObject1 = new int[] { i };
      str = "CO";
      add((int[])localObject1, str);
      i = 773;
      localObject1 = new int[] { i };
      str = "UY";
      add((int[])localObject1, str);
      i = 775;
      localObject1 = new int[] { i };
      str = "PE";
      add((int[])localObject1, str);
      i = 777;
      localObject1 = new int[] { i };
      str = "BO";
      add((int[])localObject1, str);
      i = 779;
      localObject1 = new int[] { i };
      str = "AR";
      add((int[])localObject1, str);
      i = 780;
      localObject1 = new int[] { i };
      str = "CL";
      add((int[])localObject1, str);
      i = 784;
      localObject1 = new int[] { i };
      str = "PY";
      add((int[])localObject1, str);
      i = 785;
      localObject1 = new int[] { i };
      str = "PE";
      add((int[])localObject1, str);
      i = 786;
      localObject1 = new int[] { i };
      str = "EC";
      add((int[])localObject1, str);
      i = 789;
      j = 790;
      localObject1 = new int[] { i, j };
      str = "BR";
      add((int[])localObject1, str);
      i = 800;
      j = 839;
      localObject1 = new int[] { i, j };
      str = "IT";
      add((int[])localObject1, str);
      i = 840;
      j = 849;
      localObject1 = new int[] { i, j };
      str = "ES";
      add((int[])localObject1, str);
      i = 850;
      localObject1 = new int[] { i };
      str = "CU";
      add((int[])localObject1, str);
      i = 858;
      localObject1 = new int[] { i };
      str = "SK";
      add((int[])localObject1, str);
      i = 859;
      localObject1 = new int[] { i };
      str = "CZ";
      add((int[])localObject1, str);
      i = 860;
      localObject1 = new int[] { i };
      str = "YU";
      add((int[])localObject1, str);
      i = 865;
      localObject1 = new int[] { i };
      str = "MN";
      add((int[])localObject1, str);
      i = 867;
      localObject1 = new int[] { i };
      str = "KP";
      add((int[])localObject1, str);
      i = 868;
      j = 869;
      localObject1 = new int[] { i, j };
      str = "TR";
      add((int[])localObject1, str);
      i = 870;
      j = 879;
      localObject1 = new int[] { i, j };
      str = "NL";
      add((int[])localObject1, str);
      i = 880;
      localObject1 = new int[] { i };
      str = "KR";
      add((int[])localObject1, str);
      i = 885;
      localObject1 = new int[] { i };
      str = "TH";
      add((int[])localObject1, str);
      i = 888;
      localObject1 = new int[] { i };
      str = "SG";
      add((int[])localObject1, str);
      i = 890;
      localObject1 = new int[] { i };
      str = "IN";
      add((int[])localObject1, str);
      i = 893;
      localObject1 = new int[] { i };
      str = "VN";
      add((int[])localObject1, str);
      i = 896;
      localObject1 = new int[] { i };
      str = "PK";
      add((int[])localObject1, str);
      i = 899;
      localObject1 = new int[] { i };
      str = "ID";
      add((int[])localObject1, str);
      i = 900;
      j = 919;
      localObject1 = new int[] { i, j };
      str = "AT";
      add((int[])localObject1, str);
      i = 930;
      j = 939;
      localObject1 = new int[] { i, j };
      str = "AU";
      add((int[])localObject1, str);
      i = 940;
      j = 949;
      localObject1 = new int[] { i, j };
      str = "AZ";
      add((int[])localObject1, str);
      i = 955;
      localObject1 = new int[] { i };
      str = "MY";
      add((int[])localObject1, str);
      i = 958;
      localObject1 = new int[] { i };
      str = "MO";
      add((int[])localObject1, str);
      return;
    }
    finally {}
  }
  
  public String lookupCountryIdentifier(String paramString)
  {
    initIfNeeded();
    paramString = paramString.substring(0, 3);
    int i = Integer.parseInt(paramString);
    List localList = this.ranges;
    int j = localList.size();
    int k = 0;
    for (;;)
    {
      int m = 0;
      if (k >= j) {
        break;
      }
      int[] arrayOfInt = (int[])this.ranges.get(k);
      int n = arrayOfInt[0];
      if (i < n) {
        return null;
      }
      m = arrayOfInt.length;
      int i1 = 1;
      if (m != i1) {
        n = arrayOfInt[i1];
      }
      if (i <= n) {
        return (String)this.countryIdentifiers.get(k);
      }
      k += 1;
    }
    return null;
  }
}


/* Location:           G:\apknx\enjarify-master\com.cunba.lantu.otan-enjarify.jar
 * Qualified Name:     com.google.zxing.oned.EANManufacturerOrgSupport
 * JD-Core Version:    0.7.0.1
 */